destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/junium-pdf"
port: 4010
output: pdf
product: jUnium
print_title: Framework for scalable and productive automated testing written with Java.
print_subtitle: version 1.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true